/*    "id": 20,
      "name": "Earth (Replacement Dimension)"
      "id": 19,
      "name": "Gromflom Prime",
      "id": 18,
      "name": "Mr. Goldenfold's dream",
      "id": 17,
      "name": "Earth (5-126)",
      "id": 16,
      "name": "St. Gloopy Noops Hospital",
      "id": 15,
      "name": "Bird World",
      "id": 14,
      "name": "Giant's Town",
      "id": 13,
      "name": "Nuptia 4",
      "id": 12,
      "name": "Cronenberg Earth",
      "id": 11,
      "name": "Bepis 9",
      "id": 3,
      "name": "Citadel of Ricks",
      "id": 2,
      "name": "Abadango",
      "id": 1,
      "name": "Earth (C-137)",
*/
